version: "3"

services:   
  postgres-db:
    image: postgres:13-alpine
    restart: always
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - '5433:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - default

  pgadmin:
    image: tophfr/pgadmin:4.25
    environment:
      SETUP_SERVER_NAME: localhost
      SETUP_SERVER_HOST: postgres-db
      SETUP_SERVER_PORT: 5433
      SETUP_SERVER_USER: postgres
      SETUP_SERVER_PASS: postgres
      MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:5050"

  app: 
    build: 
      context: .
    ports: 
      - "8000:8000"
    volumes: 
      - ./backend:/app/backend
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment: 
      - DEBUG=1 
    depends_on: 
      - postgres-db
    networks:
      - default
volumes:
  db-data:
networks:
  default:
    driver: bridge