# Generated by Django 3.1.7 on 2021-03-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(choices=[(1, 'Floor1'), (2, 'Floor2')])),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
