# Generated by Django 3.1.7 on 2021-04-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='points',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
