# Generated by Django 3.1.7 on 2021-05-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20210510_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='remember_token_expire',
            field=models.DateTimeField(blank=True, verbose_name=''),
        ),
    ]
