# Generated by Django 3.1.7 on 2021-05-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20210510_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='remember_token_expire',
            field=models.DateTimeField(blank=True, null=True, verbose_name=''),
        ),
    ]
